import {
  ReactNode,
  useEffect,
  useMemo,
  useState,
  type KeyboardEvent as ReactKeyboardEvent,
} from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Menu, X, Moon, Sun, Search, ExternalLink, FileText } from 'lucide-react';
import { Sidebar } from './Sidebar';
import { cn } from '@/lib/utils';

interface LayoutProps {
  children: ReactNode;
  darkMode: boolean;
  setDarkMode: (value: boolean) => void;
}

interface SearchDoc {
  title: string;
  section: string;
  href: string;
  headings: string[];
  body: string;
}

interface SearchResult {
  doc: SearchDoc;
  score: number;
  snippet: string;
}

// Generated by scripts/build-search-index.mjs; fetched once, then cached.
let indexPromise: Promise<SearchDoc[]> | null = null;
function loadSearchIndex(): Promise<SearchDoc[]> {
  if (!indexPromise) {
    indexPromise = fetch(`${import.meta.env.BASE_URL}search-index.json`)
      .then((res) => (res.ok ? res.json() : []))
      .catch(() => []);
  }
  return indexPromise;
}

function searchDocs(index: SearchDoc[], query: string): SearchResult[] {
  const tokens = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (tokens.length === 0) return [];

  const results: SearchResult[] = [];
  for (const doc of index) {
    const title = doc.title.toLowerCase();
    const headings = doc.headings.join(' ').toLowerCase();
    const body = doc.body.toLowerCase();

    let score = 0;
    let matchedAll = true;
    for (const token of tokens) {
      let tokenScore = 0;
      if (title.includes(token)) tokenScore += 10;
      if (headings.includes(token)) tokenScore += 4;
      if (body.includes(token)) tokenScore += 1;
      if (tokenScore === 0) {
        matchedAll = false;
        break;
      }
      score += tokenScore;
    }
    if (!matchedAll) continue;

    const at = body.indexOf(tokens[0]);
    const snippet =
      at >= 0
        ? (at > 40 ? '…' : '') +
          doc.body.slice(Math.max(0, at - 40), at + 90).trim() +
          '…'
        : doc.body.slice(0, 130) + '…';
    results.push({ doc, score, snippet });
  }
  return results.sort((a, b) => b.score - a.score).slice(0, 8);
}

export function Layout({ children, darkMode, setDarkMode }: LayoutProps) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [index, setIndex] = useState<SearchDoc[] | null>(null);
  const [selected, setSelected] = useState(0);
  const navigate = useNavigate();

  useEffect(() => {
    function onKeyDown(e: KeyboardEvent) {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        setSearchOpen(true);
      } else if (e.key === 'Escape') {
        setSearchOpen(false);
      }
    }
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, []);

  useEffect(() => {
    if (searchOpen && !index) {
      loadSearchIndex().then(setIndex);
    }
    if (!searchOpen) {
      setQuery('');
      setSelected(0);
    }
  }, [searchOpen, index]);

  const results = useMemo(
    () => (index ? searchDocs(index, query) : []),
    [index, query]
  );

  useEffect(() => setSelected(0), [query]);

  function openResult(href: string) {
    setSearchOpen(false);
    navigate(href);
  }

  function onSearchKeyDown(e: ReactKeyboardEvent<HTMLInputElement>) {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setSelected((s) => Math.min(s + 1, results.length - 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setSelected((s) => Math.max(s - 1, 0));
    } else if (e.key === 'Enter' && results[selected]) {
      openResult(results[selected].doc.href);
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 w-full border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="flex h-14 items-center px-4 lg:px-6">
          {/* Mobile menu button */}
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="mr-2 p-2 lg:hidden hover:bg-muted rounded-md"
          >
            {sidebarOpen ? <X size={20} /> : <Menu size={20} />}
          </button>

          {/* Logo */}
          <Link to="/" className="flex items-center mr-6">
            <img
              src={`${import.meta.env.BASE_URL}transparent_logo.png`}
              alt="Groovy Security"
              className="h-8 w-8"
            />
            <img
              src={`${import.meta.env.BASE_URL}textonly_nobuffer.png`}
              alt="Groovy Security"
              className="ml-2 h-5 object-contain hidden sm:inline-block"
            />
            <span className="ml-2 text-sm font-medium text-muted-foreground hidden sm:inline-block">
              Docs
            </span>
          </Link>

          {/* Search (desktop) */}
          <div className="flex-1 max-w-md hidden md:block">
            <button
              onClick={() => setSearchOpen(true)}
              className="w-full flex items-center gap-2 px-3 py-1.5 text-sm text-muted-foreground bg-muted rounded-md hover:bg-muted/80 transition-colors"
            >
              <Search size={16} />
              <span>Search documentation...</span>
              <kbd className="ml-auto text-xs bg-background px-1.5 py-0.5 rounded border border-border">
                ⌘K
              </kbd>
            </button>
          </div>

          {/* Right side actions */}
          <div className="ml-auto flex items-center gap-2">
            {/* Search (mobile) */}
            <button
              onClick={() => setSearchOpen(true)}
              className="p-2 md:hidden hover:bg-muted rounded-md"
            >
              <Search size={20} />
            </button>

            {/* Dark mode toggle */}
            <button
              onClick={() => setDarkMode(!darkMode)}
              className="p-2 hover:bg-muted rounded-md"
              aria-label="Toggle dark mode"
            >
              {darkMode ? <Sun size={20} /> : <Moon size={20} />}
            </button>

            {/* Back to main site */}
            <a
              href="https://groovysec.com"
              target="_blank"
              rel="noopener noreferrer"
              className="hidden sm:flex items-center gap-1 px-3 py-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              groovysec.com
              <ExternalLink size={14} />
            </a>
          </div>
        </div>
      </header>

      <div className="flex">
        {/* Sidebar */}
        <aside
          className={cn(
            'fixed inset-y-0 left-0 z-40 w-64 pt-14 bg-background border-r border-border transform transition-transform duration-200 lg:translate-x-0 lg:static lg:pt-0',
            sidebarOpen ? 'translate-x-0' : '-translate-x-full'
          )}
        >
          <Sidebar onNavigate={() => setSidebarOpen(false)} />
        </aside>

        {/* Overlay for mobile */}
        {sidebarOpen && (
          <div
            className="fixed inset-0 z-30 bg-black/50 lg:hidden"
            onClick={() => setSidebarOpen(false)}
          />
        )}

        {/* Main content */}
        <main className="flex-1 min-w-0">
          <div className="max-w-4xl mx-auto px-4 py-8 lg:px-8">
            {children}
          </div>
        </main>
      </div>

      {/* Search modal */}
      {searchOpen && (
        <div
          className="fixed inset-0 z-50 bg-black/50 flex items-start justify-center pt-20"
          onClick={() => setSearchOpen(false)}
        >
          <div
            className="bg-background rounded-lg shadow-xl w-full max-w-lg mx-4 p-4"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center gap-2 mb-4">
              <Search size={20} className="text-muted-foreground" />
              <input
                type="text"
                placeholder="Search documentation..."
                className="flex-1 bg-transparent outline-none text-lg"
                autoFocus
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                onKeyDown={onSearchKeyDown}
              />
              <button
                onClick={() => setSearchOpen(false)}
                className="p-1 hover:bg-muted rounded"
              >
                <X size={20} />
              </button>
            </div>
            {query.trim() === '' ? (
              <p className="text-sm text-muted-foreground">
                Start typing to search...
              </p>
            ) : results.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                {index ? `No results for "${query}"` : 'Loading search index…'}
              </p>
            ) : (
              <ul className="max-h-80 overflow-y-auto -mx-2 px-2">
                {results.map((result, i) => (
                  <li key={result.doc.href}>
                    <button
                      onClick={() => openResult(result.doc.href)}
                      onMouseEnter={() => setSelected(i)}
                      className={cn(
                        'w-full text-left px-3 py-2.5 rounded-md flex items-start gap-3',
                        i === selected ? 'bg-muted' : ''
                      )}
                    >
                      <FileText
                        size={16}
                        className="mt-1 text-muted-foreground flex-shrink-0"
                      />
                      <span className="min-w-0">
                        <span className="block text-sm font-medium">
                          {result.doc.title}
                          <span className="ml-2 text-xs font-normal text-muted-foreground">
                            {result.doc.section}
                          </span>
                        </span>
                        <span className="block text-xs text-muted-foreground truncate">
                          {result.snippet}
                        </span>
                      </span>
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
